import type { Metadata } from 'next';
import React, { JSX } from 'react';
import '../../../styles/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by (.)create next app',
};

const BackendRootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element => {
  return (
    <html lang="en">
      <body>
        <div id="root">
          <main className="container scrollable">{children}</main>
        </div>
      </body>
    </html>
  );
};

export default BackendRootLayout;
